name: Build Feeds

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (UTC)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip requests
      - run: python scripts/merge_feeds.py
      - name: Commit updated feeds
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/*.txt
          git commit -m "Update feeds" || echo "No changes"
          git push
