name: Build Feeds

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (UTC)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip requests
      - run: python scripts/merge_feeds.py
      - name: Commit updated feeds
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/*.txt
# … your existing build steps …

- name: Build feeds
  run: |
    python scripts/merge_feeds.py
    mkdir -p dist
    cp docs/*.txt dist/   # or write your script to output directly into dist/

# Publish to GitHub Pages without committing files
- name: Upload Pages artifact
  uses: actions/upload-pages-artifact@v3
  with:
    path: dist

- name: Deploy to GitHub Pages
  id: deploy
  uses: actions/deploy-pages@v4

